// This file is auto-generated by @hey-api/openapi-ts

export const $Gender = {
  type: 'string',
  enum: ['male', 'female', 'other'],
  title: 'Gender'
} as const

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError'
      },
      type: 'array',
      title: 'Detail'
    }
  },
  type: 'object',
  title: 'HTTPValidationError'
} as const

export const $InventoryCreate = {
  properties: {
    item_id: {
      type: 'integer',
      title: 'Item Id'
    },
    quantity: {
      type: 'integer',
      title: 'Quantity'
    }
  },
  type: 'object',
  required: ['item_id', 'quantity'],
  title: 'InventoryCreate'
} as const

export const $ReportCreate = {
  properties: {
    survivor_id: {
      type: 'integer',
      title: 'Survivor Id'
    },
    reporter_id: {
      anyOf: [
        {
          type: 'integer'
        },
        {
          type: 'null'
        }
      ],
      title: 'Reporter Id'
    }
  },
  type: 'object',
  required: ['survivor_id'],
  title: 'ReportCreate'
} as const

export const $SuccessResponse = {
  properties: {
    message: {
      type: 'string',
      title: 'Message'
    }
  },
  type: 'object',
  required: ['message'],
  title: 'SuccessResponse'
} as const

export const $SurvivalLocationUpdateResponse = {
  properties: {
    latitude: {
      type: 'number',
      title: 'Latitude'
    },
    longitude: {
      type: 'number',
      title: 'Longitude'
    },
    id: {
      type: 'integer',
      title: 'Id'
    }
  },
  type: 'object',
  required: ['latitude', 'longitude', 'id'],
  title: 'SurvivalLocationUpdateResponse'
} as const

export const $Survivor = {
  properties: {
    latitude: {
      type: 'number',
      title: 'Latitude'
    },
    longitude: {
      type: 'number',
      title: 'Longitude'
    },
    name: {
      type: 'string',
      title: 'Name'
    },
    age: {
      type: 'integer',
      title: 'Age'
    },
    gender: {
      $ref: '#/components/schemas/Gender'
    },
    id: {
      anyOf: [
        {
          type: 'integer'
        },
        {
          type: 'null'
        }
      ],
      title: 'Id'
    },
    is_infected: {
      type: 'boolean',
      title: 'Is Infected',
      default: false
    }
  },
  type: 'object',
  required: ['latitude', 'longitude', 'name', 'age', 'gender'],
  title: 'Survivor'
} as const

export const $SurvivorCreate = {
  properties: {
    latitude: {
      type: 'number',
      title: 'Latitude'
    },
    longitude: {
      type: 'number',
      title: 'Longitude'
    },
    name: {
      type: 'string',
      title: 'Name'
    },
    age: {
      type: 'integer',
      title: 'Age'
    },
    gender: {
      $ref: '#/components/schemas/Gender'
    },
    inventory: {
      items: {
        $ref: '#/components/schemas/InventoryCreate'
      },
      type: 'array',
      title: 'Inventory'
    }
  },
  type: 'object',
  required: [
    'latitude',
    'longitude',
    'name',
    'age',
    'gender',
    'inventory'
  ],
  title: 'SurvivorCreate'
} as const

export const $SurvivorLocationUpdate = {
  properties: {
    latitude: {
      type: 'number',
      title: 'Latitude'
    },
    longitude: {
      type: 'number',
      title: 'Longitude'
    },
    survivor_id: {
      type: 'integer',
      title: 'Survivor Id'
    }
  },
  type: 'object',
  required: ['latitude', 'longitude', 'survivor_id'],
  title: 'SurvivorLocationUpdate'
} as const

export const $Trade = {
  properties: {
    from_survivor_id: {
      type: 'integer',
      title: 'From Survivor Id'
    },
    to_survivor_id: {
      type: 'integer',
      title: 'To Survivor Id'
    },
    from_items: {
      items: {
        $ref: '#/components/schemas/TradeItem'
      },
      type: 'array',
      title: 'From Items'
    },
    to_items: {
      items: {
        $ref: '#/components/schemas/TradeItem'
      },
      type: 'array',
      title: 'To Items'
    }
  },
  type: 'object',
  required: [
    'from_survivor_id',
    'to_survivor_id',
    'from_items',
    'to_items'
  ],
  title: 'Trade'
} as const

export const $TradeItem = {
  properties: {
    item_id: {
      type: 'integer',
      title: 'Item Id'
    },
    quantity: {
      type: 'integer',
      title: 'Quantity'
    }
  },
  type: 'object',
  required: ['item_id', 'quantity'],
  title: 'TradeItem'
} as const

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string'
          },
          {
            type: 'integer'
          }
        ]
      },
      type: 'array',
      title: 'Location'
    },
    msg: {
      type: 'string',
      title: 'Message'
    },
    type: {
      type: 'string',
      title: 'Error Type'
    }
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError'
} as const
