// This file is auto-generated by @hey-api/openapi-ts

export type Gender = 'male' | 'female' | 'other'

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type InventoryCreate = {
  item_id: number
  quantity: number
}

export type InventoryItemPublic = {
  name: ItemName
  points: number
  id: number
}

export type ItemName = 'water' | 'food' | 'medication' | 'ammunition'

export type ReportCreate = {
  survivor_id: number
  reporter_id?: number | null
}

export type SuccessResponse = {
  message: string
}

export type SurvivalLocationUpdateResponse = {
  latitude: number
  longitude: number
  id: number
}

export type Survivor = {
  latitude: number
  longitude: number
  name: string
  age: number
  gender: Gender
  id?: number | null
  is_infected?: boolean
}

export type SurvivorCreate = {
  latitude: number
  longitude: number
  name: string
  age: number
  gender: Gender
  inventory: Array<InventoryCreate>
}

export type SurvivorLocationUpdate = {
  latitude: number
  longitude: number
  survivor_id: number
}

export type Trade = {
  from_survivor_id: number
  to_survivor_id: number
  from_items: Array<TradeItem>
  to_items: Array<TradeItem>
}

export type TradeItem = {
  item_id: number
  quantity: number
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ReadRootResponse = SuccessResponse

export type ReadSurvivorsResponse = Array<Survivor>

export type CreateSurvivorData = {
  requestBody: SurvivorCreate
}

export type CreateSurvivorResponse = Survivor

export type ReadSurvivorData = {
  survivorId: number
}

export type ReadSurvivorResponse = Survivor

export type UpdateSurvivorLocationData = {
  requestBody: SurvivorLocationUpdate
}

export type UpdateSurvivorLocationResponse =
  SurvivalLocationUpdateResponse

export type ReportInfectionData = {
  requestBody: ReportCreate
}

export type ReportInfectionResponse = SuccessResponse

export type TradeItemsData = {
  requestBody: Trade
}

export type TradeItemsResponse = SuccessResponse

export type GetInventoryItemsResponse = Array<InventoryItemPublic>

export type $OpenApiTs = {
  '/': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: SuccessResponse
      }
    }
  }
  '/survivors/': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<Survivor>
      }
    }
    post: {
      req: CreateSurvivorData
      res: {
        /**
         * Successful Response
         */
        201: Survivor
        /**
         * Validation Error
         */
        422: HTTPValidationError
      }
    }
  }
  '/survivors/{survivor_id}/': {
    get: {
      req: ReadSurvivorData
      res: {
        /**
         * Successful Response
         */
        200: Survivor
        /**
         * Validation Error
         */
        422: HTTPValidationError
      }
    }
  }
  '/survivors/location/': {
    patch: {
      req: UpdateSurvivorLocationData
      res: {
        /**
         * Successful Response
         */
        200: SurvivalLocationUpdateResponse
        /**
         * Validation Error
         */
        422: HTTPValidationError
      }
    }
  }
  '/survivors/report/': {
    post: {
      req: ReportInfectionData
      res: {
        /**
         * Successful Response
         */
        201: SuccessResponse
        /**
         * Validation Error
         */
        422: HTTPValidationError
      }
    }
  }
  '/trade/': {
    post: {
      req: TradeItemsData
      res: {
        /**
         * Successful Response
         */
        200: SuccessResponse
        /**
         * Validation Error
         */
        422: HTTPValidationError
      }
    }
  }
  '/inventory-items/': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<InventoryItemPublic>
      }
    }
  }
}
