// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { RootReadRootResponse, SurvivorsReadSurvivorsEndpointResponse, SurvivorsCreateSurvivorEndpointData, SurvivorsCreateSurvivorEndpointResponse, SurvivorsReadSurvivorEndpointData, SurvivorsReadSurvivorEndpointResponse, SurvivorsUpdateSurvivorLocationEndpointData, SurvivorsUpdateSurvivorLocationEndpointResponse, SurvivorsReportInfectionEndpointData, SurvivorsReportInfectionEndpointResponse, TradeTradeItemsEndpointData, TradeTradeItemsEndpointResponse } from './types.gen';

export class RootService {
    /**
     * Read Root
     * @returns SuccessResponse Successful Response
     * @throws ApiError
     */
    public static rootReadRoot(): CancelablePromise<RootReadRootResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
}

export class SurvivorsService {
    /**
     * Read Survivors Endpoint
     * @returns Survivor Successful Response
     * @throws ApiError
     */
    public static survivorsReadSurvivorsEndpoint(): CancelablePromise<SurvivorsReadSurvivorsEndpointResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/survivors/'
        });
    }
    
    /**
     * Create Survivor Endpoint
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Survivor Successful Response
     * @throws ApiError
     */
    public static survivorsCreateSurvivorEndpoint(data: SurvivorsCreateSurvivorEndpointData): CancelablePromise<SurvivorsCreateSurvivorEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/survivors/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Survivor Endpoint
     * @param data The data for the request.
     * @param data.survivorId
     * @returns Survivor Successful Response
     * @throws ApiError
     */
    public static survivorsReadSurvivorEndpoint(data: SurvivorsReadSurvivorEndpointData): CancelablePromise<SurvivorsReadSurvivorEndpointResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/survivors/{survivor_id}/',
            path: {
                survivor_id: data.survivorId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Survivor Location Endpoint
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SurvivalLocationUpdateResponse Successful Response
     * @throws ApiError
     */
    public static survivorsUpdateSurvivorLocationEndpoint(data: SurvivorsUpdateSurvivorLocationEndpointData): CancelablePromise<SurvivorsUpdateSurvivorLocationEndpointResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/survivors/location/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Report Infection Endpoint
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SuccessResponse Successful Response
     * @throws ApiError
     */
    public static survivorsReportInfectionEndpoint(data: SurvivorsReportInfectionEndpointData): CancelablePromise<SurvivorsReportInfectionEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/survivors/report/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class TradeService {
    /**
     * Trade Items Endpoint
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SuccessResponse Successful Response
     * @throws ApiError
     */
    public static tradeTradeItemsEndpoint(data: TradeTradeItemsEndpointData): CancelablePromise<TradeTradeItemsEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/trade/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}